### ISSUE TITLE
Identifying training and validation examples for OWL learning problems

### ISSUE THREAD

**Issue by idanivanov** [SmartDataAnalytics/SML-Bench#5]
I am trying to add my own tool to the framework working with OWL. As I understand, the training examples are defined by the learning problem and can be found in:
./learningtasks/[task_id]/owl/[lp_id]/
My question is: are the validation examples defined as a different learning problem or is there some other way of identifying them?
E.g.:
Training examples: ./learningtasks/[task_id]/owl/[lp_train_id]/
Validation examples: ./learningtasks/[task_id]/owl/[lp_validation_id]/

Also, is there a possibility to know the complete set of examples during the learning step? (I am asking because I need to do feature extraction and I have to maintain a consistent state for all training and validation examples)

**Comment by patrickwestphal** [comment]
The idea is to keep all the examples in one learning problem. The framework should take care of splitting the example sets accordingly (n-fold cross validation, test/validation set, ...) if configured. But this is yet to be implemented, unfortunately. However, then your `run` and `validate` executables would only see the fold they are currently working on.
Accordingly, to have access to all examples, though working only on a training split, you would probably have to do the splitting in your `run`/`validate` executable. (Kind of hard coded, e.g. shuffle with fixed seed and take first 70% in `run` and last 30% in `validate` etc.) So it seems we currently do not cover your use case or your tool requirements. :( But we would be happy to support it in the future, if possible. May I ask for further details of your tool? Is your tool/source code accessible somewhere on the Web?

**Comment by idanivanov** [comment]
Thank you for the information. Then I will do for now the split in the `run` / `validate` files.

The tool is available here:
https://github.com/idanivanov/master_thesis
Unfortunately, there is no documentation. The basic idea of the method is to do feature extraction from graphs by building the canonical representation of each graph instance (works only for graphs of tree-width < 4) and extracting the set of all fixed size substrings of this representation as features.

I have one more question: For the Carcinogenesis (OWL) dataset, do the 101 instances in `lp/1/` constitute the whole learning problem?

**Comment by patrickwestphal** [comment]
I took them from the [DL-Learner GitHub repository](https://github.com/AKSW/DL-Learner/blob/develop/examples/carcinogenesis/param-celoe.conf). I already noticed that there are more negative examples given in the Prolog version of the data and added them in 84a71c22d267fb427948d28563fb094306475cca . There should be all examples in now (based on the [Prolog data](https://github.com/AKSW/DL-Learner/blob/develop/examples/carcinogenesis/prolog/train.f)). If you have a more comprehensive data source, please let me know. :)

**Comment by idanivanov** [comment]
I found this page: https://relational.fit.cvut.cz/dataset/Carcinogenesis
Where it is stated that: The dataset contains 182 positive carcinogenecity tests and 148 negative tests.
I hope this helps.

**Comment by patrickwestphal** [comment]
Thank you! I'll have a look.
